### ISSUE TITLE
Deprecated Resource

### ISSUE THREAD

**Issue by AnkithaBH** [clouddrove/terraform-azure-flexible-mysql#56]
Hello Team,

We tested the module and we see that the **azurerm_mysql_server_key** is about to get deprecated.

Facing the below error,
 Warning: Deprecated Resource
│
│   with module.mysql_flexible_server.azurerm_mysql_server_key.main,
│   on ..\..\main.tf line 132, in resource "azurerm_mysql_server_key" "main":
│  132: resource "azurerm_mysql_server_key" "main" {
│
│ Azure Database for MySQL Single Server and its sub resources are scheduled for retirement by 2024-09-16 and will   
│ migrate to using Azure Database for MySQL Flexible Server: https://go.microsoft.com/fwlink/?linkid=2216041. The    
│ `azurerm_mysql_server_key` resource is deprecated and will be removed in v4.0 of the AzureRM Provider. Please use  
│ the `customer_managed_key` property of the `azurerm_mysql_flexible_server` resource instead.

If the team will able to mitigate this and add the necessary modifications along with this PR, https://github.com/clouddrove/terraform-azure-flexible-mysql/pull/55
It will be great. We can use this module internally.

Requesting to maintain the condition of using this particular configuration with count.

Thanks & Kind Regards,
Ankitha

**Comment by d4kverma** [comment]
Thanks to rasie the issue, Our team is working on this issue.

**Comment by d4kverma** [comment]
Updated new tag 
2.0.0
